export const MENUS = {
  VEGGIE: {
    name: "베지",
    kcal: 209,
    protein: 9.2,
    saturatedFat: 0.6,
    sugars: 7.6,
    sodium: 262,
  },
  EGG_Mayo: {
    name: "에그마요",
    kcal: 416,
    protein: 16.4,
    saturatedFat: 4.8,
    sugars: 7.7,
    sodium: 554,
  },
  HAM: {
    name: "햄",
    kcal: 262,
    protein: 19,
    saturatedFat: 1,
    sugars: 8.4,
    sodium: 680,
  },
  TUNA: {
    name: "참치",
    kcal: 316,
    protein: 26.9,
    saturatedFat: 1.4,
    sugars: 7.6,
    sodium: 535,
  },
  CHICKEN_SLICE: {
    name: "치킨 슬라이스",
    kcal: 265,
    protein: 18.6,
    saturatedFat: 0.9,
    sugars: 8.7,
    sodium: 751,
  },
  BLT: {
    name: "비엘티",
    kcal: 300,
    protein: 15.9,
    saturatedFat: 3.7,
    sugars: 7.9,
    sodium: 666,
  },
  ITALIAN_BMT: {
    name: "이탈리안 비엠티",
    kcal: 388,
    protein: 21,
    saturatedFat: 5.9,
    sugars: 8.6,
    sodium: 1064,
  },
  SPICY_ITALIAN: {
    name: "스파이시 이탈리안",
    kcal: 464,
    protein: 20.7,
    saturatedFat: 9.1,
    sugars: 8.7,
    sodium: 1250,
  },
  CHICKEN_TERIYAKI: {
    name: "치킨 데리야끼",
    kcal: 314,
    protein: 26.5,
    saturatedFat: 1.2,
    sugars: 10.1,
    sodium: 698,
  },
  SUBWAY_CLUB: {
    name: "써브웨이 클럽",
    kcal: 299,
    protein: 19.8,
    saturatedFat: 2.4,
    sugars: 8.53,
    sodium: 853,
  },
  PULLED_PORK_BARBECUE: {
    name: "풀드 포크 바비큐",
    kcal: 327,
    protein: 24.8,
    saturatedFat: 2.1,
    sugars: 7.8,
    sodium: 689,
  },
  K_BBQ: {
    name: "K-바비큐",
    kcal: 372,
    protein: 25.6,
    saturatedFat: 2.1,
    sugars: 14.7,
    sodium: 899,
  },
  ROTISSERIE_BARBECUE_CHICKEN: {
    name: "로티세리 바비큐 치킨",
    kcal: 327,
    protein: 29.1,
    saturatedFat: 2.5,
    sugars: 7.8,
    sodium: 542,
  },
  ROASTED_CHICKEN: {
    name: "로스트 치킨",
    kcal: 300,
    protein: 26,
    saturatedFat: 1.3,
    sugars: 8.7,
    sodium: 605,
  },
  CHICKEN_BACON_AVOCADO: {
    name: "치킨 베이컨 아보카도",
    kcal: 355,
    protein: 20.2,
    saturatedFat: 3.2,
    sugars: 9.0,
    sodium: 940,
  },
  STEAK_AND_CHEESE: {
    name: "스테이크 & 치즈",
    kcal: 355,
    protein: 28.1,
    saturatedFat: 4.2,
    sugars: 8.8,
    sodium: 780,
  },
  NEW_SPICY_SHRIMP: {
    name: "뉴 스파이시 쉬림프",
    kcal: 245,
    protein: 16.5,
    saturatedFat: 0.9,
    sugars: 9.1,
    sodium: 570,
  },
  NEW_SHRIMP: {
    name: "뉴 쉬림프",
    kcal: 241,
    protein: 16.3,
    saturatedFat: 0.6,
    sugars: 7.9,
    sodium: 415,
  },
};

export const BREADS = {
  WHITE: {
    name: "화이트",
    kcal: 202,
    protein: 6.1,
    saturatedFat: 0.3,
    sugars: 2.8,
    sodium: 343,
  },
  PARMESAN_OREGANO: {
    name: "파마산 오레가노",
    kcal: 213,
    protein: 6.3,
    saturatedFat: 0.4,
    sugars: 3.2,
    sodium: 489,
  },
  WHEAT: {
    name: "위트",
    kcal: 192,
    protein: 8.4,
    saturatedFat: 0.5,
    sugars: 5,
    sodium: 257,
  },
  HONEY_OAT: {
    name: "허니오트",
    kcal: 235,
    protein: 8.8,
    saturatedFat: 0.6,
    sugars: 9.3,
    sodium: 306,
  },
  HEARTY: {
    name: "하티",
    kcal: 210,
    protein: 7,
    saturatedFat: 1,
    sugars: 3,
    sodium: 340,
  },
  FLATBREAD: {
    name: "플랫브레드",
    kcal: 467,
    protein: 16.2,
    saturatedFat: 1.7,
    sugars: 3.9,
    sodium: 936,
  },
};

export const CHEESES = {
  AMERICAN_CHEESE: {
    name: "아메리칸치즈",
    kcal: 35.3,
    protein: 1.8,
    saturatedFat: 1.9,
    sugars: 0.4,
    sodium: 193,
  },
  SHREDDED_CHEESE: {
    name: "슈레드치즈",
    kcal: 53.6,
    protein: 3.2,
    saturatedFat: 2.4,
    sugars: 0,
    sodium: 84.7,
  },
  MOZZARELLA_CHEESE: {
    name: "모차렐라치즈",
    kcal: 43.8,
    protein: 2.8,
    saturatedFat: 2.1,
    sugars: 0.2,
    sodium: 82.3,
  },
};

export const SAUCES = {
  MUSTARD: {
    name: "머스타드",
    kcal: 15.3,
    protein: 1.1,
    saturatedFat: 0.1,
    sugars: 0.2,
    sodium: 193,
  },
  RED_WINE_VINEGAR: {
    name: "레드 와인 식초",
    kcal: 0.7,
    protein: 0,
    saturatedFat: 0,
    sugars: 0,
    sodium: 0,
  },
  SWEET_ONION: {
    name: "스위트 어니언",
    kcal: 40.1,
    protein: 0.1,
    saturatedFat: 0,
    sugars: 8.2,
    sodium: 81.7,
  },
  HONEY_MUSTARD: {
    name: "허니 머스타드",
    kcal: 38.4,
    protein: 0.4,
    saturatedFat: 0.4,
    sugars: 6.3,
    sodium: 145,
  },
  SWEET_CHILI: {
    name: "스위트 칠리",
    kcal: 40,
    protein: 0.1,
    saturatedFat: 0,
    sugars: 9.2,
    sodium: 163,
  },
  SMOKE_BBQ: {
    name: "스모크 바베큐",
    kcal: 32.8,
    protein: 0.2,
    saturatedFat: 0.1,
    sugars: 7,
    sodium: 132,
  },
  RANCH: {
    name: "랜치",
    kcal: 116,
    protein: 0.3,
    saturatedFat: 2.1,
    sugars: 0.6,
    sodium: 128,
  },
  MAYONNAISE: {
    name: "마요네즈",
    kcal: 158,
    protein: 0.3,
    saturatedFat: 2.8,
    sugars: 0.1,
    sodium: 98.1,
  },
  HOT_CHILI: {
    name: "핫 칠리",
    kcal: 41.8,
    protein: 0.2,
    saturatedFat: 0.1,
    sugars: 5.3,
    sodium: 180,
  },
  SOUTHWEST_CHIPOTLE: {
    name: "사우스웨스트 치폴레",
    kcal: 96.5,
    protein: 0.4,
    saturatedFat: 1.6,
    sugars: 1,
    sodium: 160,
  },
  HORSERADISH: {
    name: "홀스래디쉬",
    kcal: 106,
    protein: 0.3,
    saturatedFat: 1.6,
    sugars: 2.6,
    sodium: 152,
  },
  OLIVE_OIL: {
    name: "올리브 오일",
    kcal: 124,
    protein: 0,
    saturatedFat: 2.1,
    sugars: 0,
    sodium: 0,
  },
};
