import Veggie from "../assets/menuImage/Veggie-Delite.png";
import EggMayo from "../assets/menuImage/Egg-Mayo.png";
import Ham from "../assets/menuImage/Ham.png";
import Tuna from "../assets/menuImage/Tuna.png";
import ChickenSlice from "../assets/menuImage/Chicken-Slice.png";
import BLT from "../assets/menuImage/B.L.T.png";
import ItalianBMT from "../assets/menuImage/Italian-B.M.T.png";
import SpicyItalian from "../assets/menuImage/Spicy-Italian.png";
import ChickenTeriyaki from "../assets/menuImage/Chicken-Teriyaki.png";
import SubwayClub from "../assets/menuImage/Subway-Club.png";
import RoastedChicken from "../assets/menuImage/Roasted-Chicken.png";
import SteakAndCheese from "../assets/menuImage/Steak-&-Cheese.png";
import SpicyShrimp from "../assets/menuImage/Spicy-Shrimp.png";
import KBBQ from "../assets/menuImage/K-BBQ.png";
import ChickenBaconAvocado from "../assets/menuImage/Chicken-Bacon-Avocado.png";
import PulledPorkBarbecue from "../assets/menuImage/Pulled-Pork-Barbecue.png";
import RotisserieBarbecueChicken from "../assets/menuImage/Rotisserie-Barbecue-Chicken.png";
import Shrimp from "../assets/menuImage/Shrimp.png";

export const BREADS = {
  WHITE: {
    name: "화이트",
    kcal: 202,
    protein: 6.1,
    saturatedFat: 0.3,
    sugars: 2.8,
    sodium: 343,
  },
  PARMESAN_OREGANO: {
    name: "파마산 오레가노",
    kcal: 213,
    protein: 6.3,
    saturatedFat: 0.4,
    sugars: 3.2,
    sodium: 489,
  },
  WHEAT: {
    name: "위트",
    kcal: 192,
    protein: 8.4,
    saturatedFat: 0.5,
    sugars: 5,
    sodium: 257,
  },
  HONEY_OAT: {
    name: "허니오트",
    kcal: 235,
    protein: 8.8,
    saturatedFat: 0.6,
    sugars: 9.3,
    sodium: 306,
  },
  HEARTY: {
    name: "하티",
    kcal: 210,
    protein: 7,
    saturatedFat: 1,
    sugars: 3,
    sodium: 340,
  },
  FLATBREAD: {
    name: "플랫브레드",
    kcal: 467,
    protein: 16.2,
    saturatedFat: 1.7,
    sugars: 3.9,
    sodium: 936,
  },
};

export const MENUS = {
  VEGGIE: {
    name: "베지",
    kcal: 209 - BREADS.WHEAT.kcal,
    protein: 9.2 - BREADS.WHEAT.protein,
    saturatedFat: 0.6 - BREADS.WHEAT.saturatedFat,
    sugars: 7.6 - BREADS.WHEAT.sugars,
    sodium: 262 - BREADS.WHEAT.sodium,
    img: Veggie,
    description: "Veggie Delite",
  },
  EGG_Mayo: {
    name: "에그마요",
    kcal: 416 - BREADS.WHEAT.kcal,
    protein: 16.4 - BREADS.WHEAT.protein,
    saturatedFat: 4.8 - BREADS.WHEAT.saturatedFat,
    sugars: 7.7 - BREADS.WHEAT.sugars,
    sodium: 554 - BREADS.WHEAT.sodium,
    img: EggMayo,
    description: "Egg Mayo",
  },
  HAM: {
    name: "햄",
    kcal: 262 - BREADS.WHEAT.kcal,
    protein: 19 - BREADS.WHEAT.protein,
    saturatedFat: 1 - BREADS.WHEAT.saturatedFat,
    sugars: 8.4 - BREADS.WHEAT.sugars,
    sodium: 680 - BREADS.WHEAT.sodium,
    img: Ham,
    description: "Ham",
  },
  TUNA: {
    name: "참치",
    kcal: 316 - BREADS.WHEAT.kcal,
    protein: 26.9 - BREADS.WHEAT.protein,
    saturatedFat: 1.4 - BREADS.WHEAT.saturatedFat,
    sugars: 7.6 - BREADS.WHEAT.sugars,
    sodium: 535 - BREADS.WHEAT.sodium,
    img: Tuna,
    description: "Tuna",
  },
  CHICKEN_SLICE: {
    name: "치킨 슬라이스",
    kcal: 265 - BREADS.WHEAT.kcal,
    protein: 18.6 - BREADS.WHEAT.protein,
    saturatedFat: 0.9 - BREADS.WHEAT.saturatedFat,
    sugars: 8.7 - BREADS.WHEAT.sugars,
    sodium: 751 - BREADS.WHEAT.sodium,
    img: ChickenSlice,
    description: "Chicken Slice",
  },
  BLT: {
    name: "비엘티",
    kcal: 300 - BREADS.WHEAT.kcal,
    protein: 15.9 - BREADS.WHEAT.protein,
    saturatedFat: 3.7 - BREADS.WHEAT.saturatedFat,
    sugars: 7.9 - BREADS.WHEAT.sugars,
    sodium: 666 - BREADS.WHEAT.sodium,
    img: BLT,
    description: "B.L.T.",
  },
  ITALIAN_BMT: {
    name: "이탈리안 비엠티",
    kcal: 388 - BREADS.WHEAT.kcal,
    protein: 21 - BREADS.WHEAT.protein,
    saturatedFat: 5.9 - BREADS.WHEAT.saturatedFat,
    sugars: 8.6 - BREADS.WHEAT.sugars,
    sodium: 1064 - BREADS.WHEAT.sodium,
    img: ItalianBMT,
    description: "Italian B.M.T.",
  },
  SPICY_ITALIAN: {
    name: "스파이시 이탈리안",
    kcal: 464 - BREADS.WHEAT.kcal,
    protein: 20.7 - BREADS.WHEAT.protein,
    saturatedFat: 9.1 - BREADS.WHEAT.saturatedFat,
    sugars: 8.7 - BREADS.WHEAT.sugars,
    sodium: 1250 - BREADS.WHEAT.sodium,
    img: SpicyItalian,
    description: "Spicy Italian",
  },
  CHICKEN_TERIYAKI: {
    name: "치킨 데리야끼",
    kcal: 314 - BREADS.WHEAT.kcal,
    protein: 26.5 - BREADS.WHEAT.protein,
    saturatedFat: 1.2 - BREADS.WHEAT.saturatedFat,
    sugars: 10.1 - BREADS.WHEAT.sugars,
    sodium: 698 - BREADS.WHEAT.sodium,
    img: ChickenTeriyaki,
    description: "Chicken Teriyaki",
  },
  SUBWAY_CLUB: {
    name: "써브웨이 클럽",
    kcal: 299 - BREADS.WHEAT.kcal,
    protein: 19.8 - BREADS.WHEAT.protein,
    saturatedFat: 2.4 - BREADS.WHEAT.saturatedFat,
    sugars: 8.53 - BREADS.WHEAT.sugars,
    sodium: 853 - BREADS.WHEAT.sodium,
    img: SubwayClub,
    description: "Subway Club",
  },
  PULLED_PORK_BARBECUE: {
    name: "풀드 포크 바비큐",
    kcal: 327 - BREADS.WHEAT.kcal,
    protein: 24.8 - BREADS.WHEAT.protein,
    saturatedFat: 2.1 - BREADS.WHEAT.saturatedFat,
    sugars: 7.8 - BREADS.WHEAT.sugars,
    sodium: 689 - BREADS.WHEAT.sodium,
    img: PulledPorkBarbecue,
    description: "Pulled Pork Barbecue",
  },
  K_BBQ: {
    name: "K-바비큐",
    kcal: 372 - BREADS.WHEAT.kcal,
    protein: 25.6 - BREADS.WHEAT.protein,
    saturatedFat: 2.1 - BREADS.WHEAT.saturatedFat,
    sugars: 14.7 - BREADS.WHEAT.sugars,
    sodium: 899 - BREADS.WHEAT.sodium,
    img: KBBQ,
    description: "K-BBQ.",
  },
  ROTISSERIE_BARBECUE_CHICKEN: {
    name: "로티세리 바비큐 치킨",
    kcal: 327 - BREADS.WHEAT.kcal,
    protein: 29.1 - BREADS.WHEAT.protein,
    saturatedFat: 2.5 - BREADS.WHEAT.saturatedFat,
    sugars: 7.8 - BREADS.WHEAT.sugars,
    sodium: 542 - BREADS.WHEAT.sodium,
    img: RotisserieBarbecueChicken,
    description: "Rotisserie Barbecue Chicken",
  },
  ROASTED_CHICKEN: {
    name: "로스트 치킨",
    kcal: 300 - BREADS.WHEAT.kcal,
    protein: 26 - BREADS.WHEAT.protein,
    saturatedFat: 1.3 - BREADS.WHEAT.saturatedFat,
    sugars: 8.7 - BREADS.WHEAT.sugars,
    sodium: 605 - BREADS.WHEAT.sodium,
    img: RoastedChicken,
    description: "Roasted Chicken",
  },
  CHICKEN_BACON_AVOCADO: {
    name: "치킨 베이컨 아보카도",
    kcal: 355 - BREADS.WHEAT.kcal,
    protein: 20.2 - BREADS.WHEAT.protein,
    saturatedFat: 3.2 - BREADS.WHEAT.saturatedFat,
    sugars: 9.0 - BREADS.WHEAT.sugars,
    sodium: 940 - BREADS.WHEAT.sodium,
    img: ChickenBaconAvocado,
    description: "Chicken Bacon Avocado",
  },
  STEAK_AND_CHEESE: {
    name: "스테이크 & 치즈",
    kcal: 355 - BREADS.WHEAT.kcal,
    protein: 28.1 - BREADS.WHEAT.protein,
    saturatedFat: 4.2 - BREADS.WHEAT.saturatedFat,
    sugars: 8.8 - BREADS.WHEAT.sugars,
    sodium: 780 - BREADS.WHEAT.sodium,
    img: SteakAndCheese,
    description: "Steak & Cheese",
  },
  NEW_SPICY_SHRIMP: {
    name: "뉴 스파이시 쉬림프",
    kcal: 245 - BREADS.WHEAT.kcal,
    protein: 16.5 - BREADS.WHEAT.protein,
    saturatedFat: 0.9 - BREADS.WHEAT.saturatedFat,
    sugars: 9.1 - BREADS.WHEAT.sugars,
    sodium: 570 - BREADS.WHEAT.sodium,
    img: SpicyShrimp,
    description: "New Spicy Shrimp",
  },
  NEW_SHRIMP: {
    name: "뉴 쉬림프",
    kcal: 241 - BREADS.WHEAT.kcal,
    protein: 16.3 - BREADS.WHEAT.protein,
    saturatedFat: 0.6 - BREADS.WHEAT.saturatedFat,
    sugars: 7.9 - BREADS.WHEAT.sugars,
    sodium: 415 - BREADS.WHEAT.sodium,
    img: Shrimp,
    description: "New Shrimp",
  },
};

export const CHEESES = {
  AMERICAN_CHEESE: {
    name: "아메리칸치즈",
    kcal: 35.3,
    protein: 1.8,
    saturatedFat: 1.9,
    sugars: 0.4,
    sodium: 193,
  },
  SHREDDED_CHEESE: {
    name: "슈레드치즈",
    kcal: 53.6,
    protein: 3.2,
    saturatedFat: 2.4,
    sugars: 0,
    sodium: 84.7,
  },
  MOZZARELLA_CHEESE: {
    name: "모차렐라치즈",
    kcal: 43.8,
    protein: 2.8,
    saturatedFat: 2.1,
    sugars: 0.2,
    sodium: 82.3,
  },
  NONE: {
    name: "선택안함",
    kcal: 0,
    protein: 0,
    saturatedFat: 0,
    sugars: 0,
    sodium: 0,
  },
};

export const SAUCES = {
  MUSTARD: {
    name: "머스타드",
    kcal: 15.3,
    protein: 1.1,
    saturatedFat: 0.1,
    sugars: 0.2,
    sodium: 193,
  },
  RED_WINE_VINEGAR: {
    name: "레드 와인 식초",
    kcal: 0.7,
    protein: 0,
    saturatedFat: 0,
    sugars: 0,
    sodium: 0,
  },
  SWEET_ONION: {
    name: "스위트 어니언",
    kcal: 40.1,
    protein: 0.1,
    saturatedFat: 0,
    sugars: 8.2,
    sodium: 81.7,
  },
  HONEY_MUSTARD: {
    name: "허니 머스타드",
    kcal: 38.4,
    protein: 0.4,
    saturatedFat: 0.4,
    sugars: 6.3,
    sodium: 145,
  },
  SWEET_CHILI: {
    name: "스위트 칠리",
    kcal: 40,
    protein: 0.1,
    saturatedFat: 0,
    sugars: 9.2,
    sodium: 163,
  },
  SMOKE_BBQ: {
    name: "스모크 바베큐",
    kcal: 32.8,
    protein: 0.2,
    saturatedFat: 0.1,
    sugars: 7,
    sodium: 132,
  },
  RANCH: {
    name: "랜치",
    kcal: 116,
    protein: 0.3,
    saturatedFat: 2.1,
    sugars: 0.6,
    sodium: 128,
  },
  MAYONNAISE: {
    name: "마요네즈",
    kcal: 158,
    protein: 0.3,
    saturatedFat: 2.8,
    sugars: 0.1,
    sodium: 98.1,
  },
  HOT_CHILI: {
    name: "핫 칠리",
    kcal: 41.8,
    protein: 0.2,
    saturatedFat: 0.1,
    sugars: 5.3,
    sodium: 180,
  },
  SOUTHWEST_CHIPOTLE: {
    name: "사우스웨스트 치폴레",
    kcal: 96.5,
    protein: 0.4,
    saturatedFat: 1.6,
    sugars: 1,
    sodium: 160,
  },
  HORSERADISH: {
    name: "홀스래디쉬",
    kcal: 106,
    protein: 0.3,
    saturatedFat: 1.6,
    sugars: 2.6,
    sodium: 152,
  },
  OLIVE_OIL: {
    name: "올리브 오일",
    kcal: 124,
    protein: 0,
    saturatedFat: 2.1,
    sugars: 0,
    sodium: 0,
  },
  PEPPER: {
    name: "후추",
    kcal: 0,
    protein: 0,
    saturatedFat: 0,
    sugars: 0,
    sodium: 0,
  },
  SALT: {
    name: "소금",
    kcal: 0,
    protein: 0,
    saturatedFat: 0,
    sugars: 0,
    sodium: 0,
  },
  NONE: {
    name: "선택안함",
    kcal: 0,
    protein: 0,
    saturatedFat: 0,
    sugars: 0,
    sodium: 0,
  },
};
