export const MENUS = {
  VEGGIE: "베지",
  EGG_Mayo: "에그마요",
  HAM: "햄",
  TUNA: "참치",
  CHICKEN_SLICE: "치킨 슬라이스",
  BLT: "비엘티",
  ITALIAN_BMT: "이탈리안 비엠티",
  SPICY_ITALIAN: "스파이시 이탈리안",
  CHICKEN_TERIYAKI: "치킨 데리야끼",
  SUBWAY_CLUB: "써브웨이 클럽",
  PULLED_PORK_BARBECUE: "풀드 포크 바비큐",
  K_BBQ: "K-바비큐",
  ROTISSERIE_BARBECUE_CHICKEN: "로티세리 바비큐 치킨",
  ROASTED_CHICKEN: "로스트 치킨",
  CHICKEN_BACON_AVOCADO: "치킨 베이컨 아보카도",
  STEAK_AND_CHEESE: "스테이크 & 치즈",
  NEW_SPICY_SHRIMP: "뉴 스파이시 쉬림프",
  NEW_SHRIMP: "뉴 쉬림프",
};
